TARGET_FIRMWARE_PATH="$(cut -d "/" -f 1 -s <<< "$TARGET_FIRMWARE")_$(cut -d "/" -f 2 -s <<< "$TARGET_FIRMWARE")"
TARGET_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES="$(GET_FLOATING_FEATURE_CONFIG "$FW_DIR/$TARGET_FIRMWARE_PATH/system/system/etc/floating_feature.xml" "SEC_FLOATING_FEATURE_COMMON_CONFIG_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES")"

if [[ "$TARGET_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES" == *"videoeditor"* ]]; then
    LOG "\033[0;33m! Nothing to do\033[0m"
    unset TARGET_FIRMWARE_PATH TARGET_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES
    return 0
fi

SET_PROP "system" "ro.unica.studio" "true"

unset TARGET_FIRMWARE_PATH TARGET_MULTIMEDIA_EDITOR_PLUGIN_PACKAGES
